// gctse GRAFICOS - EXTERIOR: em que PAIS fica cada cidade de votacao.
// O TSE publica o voto do exterior por CIDADE (a "UF" ZZ). Para a tela
// "Brasileiros no exterior" somar por pais, esta tabela diz o pais de cada
// cidade. E geografia (tabela da emissora), nao numero de votacao: os votos
// continuam sendo so os do TSE.
//
// Chave = nome da cidade como o TSE escreve, em MAIUSCULAS e SEM ACENTO.
// Cidade que nao estiver aqui entra em "OUTROS PAISES" e aparece na pagina
// index.html ("cidades do exterior sem pais") - acrescente aqui e F5.
window.GCTSE_EXTERIOR_PAISES = {
  // America do Norte
  "NOVA YORK": "ESTADOS UNIDOS", "NOVA IORQUE": "ESTADOS UNIDOS", "NEW YORK": "ESTADOS UNIDOS", "MIAMI": "ESTADOS UNIDOS", "BOSTON": "ESTADOS UNIDOS",
  "WASHINGTON": "ESTADOS UNIDOS", "ATLANTA": "ESTADOS UNIDOS", "CHICAGO": "ESTADOS UNIDOS", "HOUSTON": "ESTADOS UNIDOS", "LOS ANGELES": "ESTADOS UNIDOS",
  "SAO FRANCISCO": "ESTADOS UNIDOS", "SAN FRANCISCO": "ESTADOS UNIDOS", "HARTFORD": "ESTADOS UNIDOS", "ORLANDO": "ESTADOS UNIDOS",
  "TORONTO": "CANADÁ", "MONTREAL": "CANADÁ", "VANCOUVER": "CANADÁ", "OTTAWA": "CANADÁ", "OTAWA": "CANADÁ",
  "CIDADE DO MEXICO": "MÉXICO", "MEXICO": "MÉXICO",
  // America Central e Caribe
  "CIDADE DO PANAMA": "PANAMÁ", "PANAMA": "PANAMÁ", "SAN JOSE": "COSTA RICA", "SAO JOSE": "COSTA RICA", "HAVANA": "CUBA",
  "SANTO DOMINGO": "REPÚBLICA DOMINICANA", "SAO DOMINGOS": "REPÚBLICA DOMINICANA", "PORTO PRINCIPE": "HAITI", "CIDADE DA GUATEMALA": "GUATEMALA",
  "TEGUCIGALPA": "HONDURAS", "SAN SALVADOR": "EL SALVADOR", "MANAGUA": "NICARÁGUA", "KINGSTON": "JAMAICA", "PORT OF SPAIN": "TRINIDAD E TOBAGO",
  "BRIDGETOWN": "BARBADOS",
  // America do Sul
  "BUENOS AIRES": "ARGENTINA", "CORDOBA": "ARGENTINA", "MENDOZA": "ARGENTINA", "ROSARIO": "ARGENTINA", "PASO DE LOS LIBRES": "ARGENTINA", "PUERTO IGUAZU": "ARGENTINA",
  "ASSUNCAO": "PARAGUAI", "CIUDAD DEL ESTE": "PARAGUAI", "CIDADE DO LESTE": "PARAGUAI", "CONCEPCION": "PARAGUAI", "ENCARNACION": "PARAGUAI",
  "PEDRO JUAN CABALLERO": "PARAGUAI", "SALTO DEL GUAIRA": "PARAGUAI",
  "MONTEVIDEU": "URUGUAI", "RIVERA": "URUGUAI", "CHUY": "URUGUAI", "ARTIGAS": "URUGUAI", "RIO BRANCO (URUGUAI)": "URUGUAI",
  "SANTIAGO": "CHILE", "LIMA": "PERU", "IQUITOS": "PERU", "BOGOTA": "COLÔMBIA", "LETICIA": "COLÔMBIA", "QUITO": "EQUADOR",
  "CARACAS": "VENEZUELA", "SANTA ELENA DE UAIREN": "VENEZUELA", "LA PAZ": "BOLÍVIA", "SANTA CRUZ DE LA SIERRA": "BOLÍVIA",
  "COCHABAMBA": "BOLÍVIA", "COBIJA": "BOLÍVIA", "GUAYARAMERIN": "BOLÍVIA", "PUERTO QUIJARRO": "BOLÍVIA", "PUERTO SUAREZ": "BOLÍVIA",
  "GEORGETOWN": "GUIANA", "LETHEM": "GUIANA", "PARAMARIBO": "SURINAME", "CAIENA": "GUIANA FRANCESA (FRANÇA)", "SAINT-GEORGES DE L'OYAPOCK": "GUIANA FRANCESA (FRANÇA)",
  // Europa
  "LISBOA": "PORTUGAL", "PORTO": "PORTUGAL", "FARO": "PORTUGAL", "COIMBRA": "PORTUGAL", "BRAGA": "PORTUGAL", "SETUBAL": "PORTUGAL",
  "LONDRES": "REINO UNIDO", "EDIMBURGO": "REINO UNIDO", "DUBLIN": "IRLANDA",
  "PARIS": "FRANÇA", "MARSELHA": "FRANÇA", "LYON": "FRANÇA", "MADRI": "ESPANHA", "BARCELONA": "ESPANHA",
  "ROMA": "ITÁLIA", "MILAO": "ITÁLIA", "NAPOLES": "ITÁLIA", "FLORENCA": "ITÁLIA",
  "BERLIM": "ALEMANHA", "MUNIQUE": "ALEMANHA", "FRANKFURT": "ALEMANHA", "HAMBURGO": "ALEMANHA",
  "ZURIQUE": "SUÍÇA", "GENEBRA": "SUÍÇA", "BERNA": "SUÍÇA", "BRUXELAS": "BÉLGICA", "HAIA": "PAÍSES BAIXOS", "ROTERDA": "PAÍSES BAIXOS", "AMSTERDA": "PAÍSES BAIXOS",
  "LUXEMBURGO": "LUXEMBURGO", "VIENA": "ÁUSTRIA", "ESTOCOLMO": "SUÉCIA", "OSLO": "NORUEGA", "COPENHAGUE": "DINAMARCA", "HELSINQUE": "FINLÂNDIA",
  "VARSOVIA": "POLÔNIA", "PRAGA": "REPÚBLICA TCHECA", "BUDAPESTE": "HUNGRIA", "BUCARESTE": "ROMÊNIA", "SOFIA": "BULGÁRIA", "ATENAS": "GRÉCIA",
  "MOSCOU": "RÚSSIA", "KIEV": "UCRÂNIA", "LIUBLIANA": "ESLOVÊNIA", "ZAGREB": "CROÁCIA", "BELGRADO": "SÉRVIA", "BRATISLAVA": "ESLOVÁQUIA",
  "VALLETA": "MALTA", "NICOSIA": "CHIPRE", "REYKJAVIK": "ISLÂNDIA", "TALIN": "ESTÔNIA", "RIGA": "LETÔNIA", "VILNIUS": "LITUÂNIA", "TIRANA": "ALBÂNIA",
  "ANDORRA LA VELLA": "ANDORRA", "MONACO": "MÔNACO", "VATICANO": "SANTA SÉ",
  // Asia e Oceania
  "TOQUIO": "JAPÃO", "NAGOIA": "JAPÃO", "HAMAMATSU": "JAPÃO", "OSAKA": "JAPÃO",
  "PEQUIM": "CHINA", "XANGAI": "CHINA", "CANTAO": "CHINA", "HONG KONG": "CHINA", "MACAU": "CHINA", "TAIPE": "TAIWAN",
  "SEUL": "COREIA DO SUL", "NOVA DELHI": "ÍNDIA", "MUMBAI": "ÍNDIA", "CINGAPURA": "CINGAPURA", "BANGCOC": "TAILÂNDIA", "JACARTA": "INDONÉSIA",
  "KUALA LUMPUR": "MALÁSIA", "MANILA": "FILIPINAS", "HANOI": "VIETNÃ", "SYDNEY": "AUSTRÁLIA", "CAMBERRA": "AUSTRÁLIA", "MELBOURNE": "AUSTRÁLIA",
  "PERTH": "AUSTRÁLIA", "BRISBANE": "AUSTRÁLIA", "WELLINGTON": "NOVA ZELÂNDIA", "AUCKLAND": "NOVA ZELÂNDIA",
  // Oriente Medio
  "TEL AVIV": "ISRAEL", "TEL AVIVE": "ISRAEL", "JERUSALEM": "ISRAEL", "RAMALA": "PALESTINA", "BEIRUTE": "LÍBANO", "AMA": "JORDÂNIA", "AMAN": "JORDÂNIA",
  "DAMASCO": "SÍRIA", "ANCARA": "TURQUIA", "ISTAMBUL": "TURQUIA", "DUBAI": "EMIRADOS ÁRABES UNIDOS", "ABU DHABI": "EMIRADOS ÁRABES UNIDOS",
  "DOHA": "CATAR", "RIAD": "ARÁBIA SAUDITA", "KUWAIT": "KUWAIT", "TEERA": "IRÃ", "BAGDA": "IRAQUE", "MASCATE": "OMÃ", "MANAMA": "BAREIN",
  // Africa
  "LUANDA": "ANGOLA", "MAPUTO": "MOÇAMBIQUE", "PRAIA": "CABO VERDE", "BISSAU": "GUINÉ-BISSAU", "SAO TOME": "SÃO TOMÉ E PRÍNCIPE",
  "PRETORIA": "ÁFRICA DO SUL", "CIDADE DO CABO": "ÁFRICA DO SUL", "JOANESBURGO": "ÁFRICA DO SUL", "CAIRO": "EGITO", "RABAT": "MARROCOS",
  "ARGEL": "ARGÉLIA", "TUNIS": "TUNÍSIA", "LAGOS": "NIGÉRIA", "ABUJA": "NIGÉRIA", "ACRA": "GANA", "ACCRA": "GANA", "DACAR": "SENEGAL",
  "NAIROBI": "QUÊNIA", "ADIS ABEBA": "ETIÓPIA", "ADDIS ABEBA": "ETIÓPIA", "KINSHASA": "REPÚBLICA DEMOCRÁTICA DO CONGO", "BRAZZAVILLE": "CONGO",
  "LIBREVILLE": "GABÃO", "MALABO": "GUINÉ EQUATORIAL", "ABIDJAN": "COSTA DO MARFIM", "IAUNDE": "CAMARÕES", "WINDHOEK": "NAMÍBIA",
  "HARARE": "ZIMBÁBUE", "LUSACA": "ZÂMBIA", "GABORONE": "BOTSUANA", "DAR ES SALAAM": "TANZÂNIA", "COTONOU": "BENIN", "LOME": "TOGO",
  "CONACRI": "GUINÉ", "BAMAKO": "MALI", "OUAGADOUGOU": "BURKINA FASO", "NUAKCHOTT": "MAURITÂNIA", "CARTUM": "SUDÃO", "TRIPOLI": "LÍBIA"
};
